"""
This script includes classes to be imported when using gemini structured schemas. See 
https://ai.google.dev/gemini-api/docs/structured-output
"""

from typing import List, Literal, Optional

from pydantic import BaseModel, Field


JSECompanyName = Literal[
    "OUTsurance Group",
    "Bid Corporation",
    "MTN Group",
    "Aspen Pharmacare",
    "NEPI Rockcastle",
    "Pepkor Holdings",
    "Naspers",
    "The Bidvest Group",
    "Sanlam",
    "Gold Fields",
    "Clicks Group",
    "Anglo American",
    "AngloGold Ashanti",
    "BHP Group",
    "Shoprite Holdings",
    "Valterra Platinum",
    "Vodacom Group",
    "Shaftesbury Capital plc",
    "Glencore",
    "Prosus",
]

ReportingUnit = Literal["units", "thousands", "millions", "billions"]

class _CompanyLevelExtData(BaseModel):
    """
    This forms part of what we'll send to gemini, since we'll need a list of these.

    Company-level external financial and operational data
    extracted from annual reports, financial statements,
    interim results and results presentations.
    """

    # Metadata
    company: JSECompanyName = Field(
        description="Canonical JSE issuer name from the allowed values."
    )

    report_date: Optional[str] = Field(
        default=None,
        description="Reporting period end date in ISO 8601 YYYY-MM-DD format."
    )

    reporting_currency: Optional[str] = Field(
        default=None,
        description=(
            "ISO 4217 uppercase currency code applying to monetary fields, "
            "for example ZAR, USD or EUR."
        )
    )

    reporting_unit: Optional[ReportingUnit] = Field(
        default=None,
        description="Decimal scale applying to monetary fields in this record. E.g. thousands, millions, billions"
        ""
    )

    source_document: Optional[str] = Field(
        default=None,
        description="Name or title of the source document."
    )

    # Core financials
    revenue: Optional[float] = Field(
        default=None,
        description="Total sales or revenue generated by the company."
    )

    cost_of_sales: Optional[float] = Field(
        default=None,
        description="Direct cost of goods or services sold, also called cost of sales or COGS."
    )

    inventory: Optional[float] = Field(
        default=None,
        description="Value of goods, raw materials or inventory held by the company."
    )

    trade_receivables: Optional[float] = Field(
        default=None,
        description="Amounts owed to the company by customers specifically classified as trade receivables."
    )

    trade_payables: Optional[float] = Field(
        default=None,
        description="Amounts owed by the company to suppliers specifically classified as trade payables."
    )

    cash_and_cash_equivalents: Optional[float] = Field(
        default=None,
        description="Cash and cash equivalents held by the company."
    )

    operating_cash_flow: Optional[float] = Field(
        default=None,
        description="Net cash generated from operating activities."
    )

    # Debt / funding
    total_debt: Optional[float] = Field(
        default=None,
        description="Total interest-bearing borrowings or debt."
    )

    short_term_debt: Optional[float] = Field(
        default=None,
        description="Interest-bearing debt due within approximately 12 months."
    )

    long_term_debt: Optional[float] = Field(
        default=None,
        description="Interest-bearing debt classified as long-term."
    )

    debt_maturity_schedule: Optional[str] = Field(
        default=None,
        description="Explicit schedule or description of when the company's borrowings mature."
    )

    debt_due_within_12_months: Optional[float] = Field(
        default=None,
        description="Total debt explicitly disclosed as maturing within the next 12 months."
    )

    debt_due_12_to_24_months: Optional[float] = Field(
        default=None,
        description="Total debt explicitly disclosed as maturing between 12 and 24 months."
    )

    undrawn_committed_facilities: Optional[float] = Field(
        default=None,
        description="Committed borrowing or credit facilities available but not currently drawn."
    )

    finance_costs: Optional[float] = Field(
        default=None,
        description="Finance costs or interest expense incurred on borrowings."
    )

    # Capex
    capital_expenditure: Optional[float] = Field(
        default=None,
        description="Capital expenditure on long-lived assets or projects."
    )

    # FX / international exposure
    foreign_revenue: Optional[float] = Field(
        default=None,
        description="Revenue explicitly disclosed as being generated outside South Africa or from foreign operations."
    )

    revenue_by_geography: Optional[str] = Field(
        default=None,
        description="Explicit breakdown of company revenue by country, region or geography."
    )

    currencies_exposed_to: List[str] = Field(
        default_factory=list,
        description=(
            "Sorted, unique ISO 4217 uppercase codes for material currencies "
            "to which the company is explicitly exposed."
        )
    )

    foreign_currency_assets: Optional[float] = Field(
        default=None,
        description="Assets explicitly disclosed as denominated in foreign currencies."
    )

    foreign_currency_liabilities: Optional[float] = Field(
        default=None,
        description="Liabilities explicitly disclosed as denominated in foreign currencies."
    )

    fx_derivative_notional: Optional[float] = Field(
        default=None,
        description="Notional value of foreign-exchange derivatives such as forwards, swaps or options."
    )

    fx_hedging_policy: Optional[str] = Field(
        default=None,
        description="Explicitly stated policy or approach for hedging foreign-exchange exposure."
    )

    # Trade / guarantees
    guarantees_outstanding: Optional[float] = Field(
        default=None,
        description="Value of guarantees outstanding or issued in relation to contractual obligations."
    )

    letters_of_credit_disclosed: Optional[float] = Field(
        default=None,
        description="Value of explicitly disclosed letters of credit."
    )

    contingent_liabilities: Optional[float] = Field(
        default=None,
        description="Value of disclosed contingent liabilities."
    )

    # Payments / operating scale
    employee_expenses: Optional[float] = Field(
        default=None,
        description="Total employee, payroll or staff-related expenses."
    )

    employee_count: Optional[int] = Field(
        default=None,
        description="Number of employees reported by the company."
    )

    dividends_paid: Optional[float] = Field(
        default=None,
        description="Cash dividends paid to shareholders during the reporting period."
    )

    tax_paid: Optional[float] = Field(
        default=None,
        description="Cash taxes paid during the reporting period."
    )

    # Working capital
    receivable_days: Optional[float] = Field(
        default=None,
        description="Explicitly disclosed or directly calculated average receivable days / DSO."
    )

    payable_days: Optional[float] = Field(
        default=None,
        description="Explicitly disclosed or directly calculated average payable days / DPO."
    )

    inventory_days: Optional[float] = Field(
        default=None,
        description="Explicitly disclosed or directly calculated inventory holding days."
    )

    cash_conversion_cycle: Optional[float] = Field(
        default=None,
        description="Cash conversion cycle, calculated as inventory days plus receivable days minus payable days."
    )

    # International trade footprint
    imports_exposure: Optional[str] = Field(
        default=None,
        description="Explicit information about imported goods, services, raw materials or international sourcing."
    )

    exports_exposure: Optional[str] = Field(
        default=None,
        description="Explicit information about exports or sales to foreign customers."
    )

    countries_of_operation: List[str] = Field(
        default_factory=list,
        description=(
            "Sorted, unique ISO 3166-1 alpha-2 country codes for countries in "
            "which the company explicitly states that it operates."
        )
    )

    foreign_subsidiaries: List[str] = Field(
        default_factory=list,
        description="Foreign subsidiaries explicitly listed or described in the document."
    )

    major_customers_suppliers: List[str] = Field(
        default_factory=list,
        description="Major customers, suppliers or counterparties explicitly identified."
    )

    # Global Markets
    commodity_exposure: List[str] = Field(
        default_factory=list,
        description="Commodities to which the company has material exposure, e.g. gold, platinum, oil or coal."
    )

    commodity_derivatives: Optional[str] = Field(
        default=None,
        description="Explicitly disclosed commodity futures, options, swaps or other commodity hedges."
    )

    interest_rate_exposure: Optional[str] = Field(
        default=None,
        description="Description of fixed-rate, floating-rate or other material interest-rate exposure."
    )

    interest_rate_derivatives: Optional[str] = Field(
        default=None,
        description="Explicitly disclosed interest-rate swaps, caps, floors or other derivatives."
    )

    # Capital markets / lending
    bond_issues: Optional[str] = Field(
        default=None,
        description="Details of bonds, notes or other debt securities issued by the company."
    )

    bond_maturity_dates: List[str] = Field(
        default_factory=list,
        description="Explicit maturity dates of bonds or debt securities."
    )

    credit_facilities_and_lenders: Optional[str] = Field(
        default=None,
        description="Details of revolving facilities, term loans, committed facilities and identified lenders."
    )

    security_collateral_on_debt: Optional[str] = Field(
        default=None,
        description="Assets, guarantees or other collateral explicitly pledged against debt."
    )

    # Forward-looking
    major_contractual_commitments: Optional[str] = Field(
        default=None,
        description="Material future contractual, capital expenditure or purchase commitments."
    )

    order_book_project_pipeline: Optional[str] = Field(
        default=None,
        description="Explicitly disclosed order book, project pipeline or major future projects."
    )

    # Investor services / market context
    assets_under_management: Optional[float] = Field(
        default=None,
        description="Assets under management reported by the company, where applicable."
    )

    market_capitalisation: Optional[float] = Field(
        default=None,
        description="Market capitalisation of the company."
    )

    share_price: Optional[float] = Field(
        default=None,
        description="Company share price for the relevant observation date."
    )

    share_return: Optional[float] = Field(
        default=None,
        description="Share-price return over the defined period."
    )

    enterprise_value: Optional[float] = Field(
        default=None,
        description="Enterprise value of the company."
    )

    credit_rating: Optional[str] = Field(
        default=None,
        description="Explicit external credit rating assigned to the company or its debt."
    )

    ownership_major_shareholders: List[str] = Field(
        default_factory=list,
        description="Major shareholders or material ownership interests explicitly identified."
    )

    extra_notes: Optional[str] = Field(
        default=None,
        description=(
            "Concise, evidence-based notes from the supplied documents that are not captured "
            "by another field and may help Syn Bank target the company."
        )
    )

class _SENSEvent(BaseModel):
    """
    This forms part of what is sent to gemini, since we'll need a list of these

    Material SENS announcement that may indicate
    a corporate banking opportunity.
    """

    company: JSECompanyName = Field(
        description="Canonical JSE issuer name to which the announcement relates."
    )

    announcement_date: Optional[str] = Field(
        default=None,
        description=(
            "Date on which the SENS announcement was published, in ISO 8601 "
            "YYYY-MM-DD format."
        )
    )

    title: Optional[str] = Field(
        default=None,
        description="Official title or headline of the SENS announcement."
    )

    source_document: Optional[str] = Field(
        default=None,
        description="Name or identifier of the source SENS document."
    )

    source_url: Optional[str] = Field(
        default=None,
        description="URL of the original SENS announcement."
    )

    event_type: Literal[
        "acquisition",
        "disposal",
        "new_debt_facility",
        "refinancing",
        "bond_issue",
        "equity_raise",
        "major_capex_project",
        "major_contract",
        "foreign_expansion",
        "restructuring",
        "liquidity_covenant_warning",
        "dividend",
        "share_buyback",
        "guarantee_project_obligation",
        "other",
    ] = Field(
        description="Classification of the material corporate event described in the announcement."
    )

    event_value: Optional[float] = Field(
        default=None,
        description="Explicit monetary value of the transaction, project, facility or event."
    )

    event_unit: Optional[ReportingUnit] = Field(
        default=None,
        description="Decimal scale applying to event_value. Null when event_value is null."
    )

    currency: Optional[str] = Field(
        default=None,
        description=(
            "ISO 4217 uppercase currency code associated with event_value. "
            "Null when event_value is null."
        )
    )

    counterparty: Optional[str] = Field(
        default=None,
        description="Counterparty explicitly involved in the transaction or event."
    )

    target_or_asset: Optional[str] = Field(
        default=None,
        description="Acquisition target, disposed asset, project, business or other relevant asset."
    )

    country: Optional[str] = Field(
        default=None,
        description=(
            "ISO 3166-1 alpha-2 code for the country materially associated "
            "with the event."
        )
    )

    expected_completion_date: Optional[str] = Field(
        default=None,
        description=(
            "Expected completion or implementation date in ISO 8601 "
            "YYYY-MM-DD format."
        )
    )

    banking_opportunities: List[
        Literal[
            "payments",
            "collections",
            "liquidity_management",
            "trade_finance",
            "guarantees",
            "fx",
            "commodities",
            "credit",
            "interest_rates",
            "debt_capital_markets",
            "equity_capital_markets",
            "corporate_finance",
            "investor_services",
        ]
    ] = Field(
        default_factory=list,
        description="Banking products reasonably associated with the disclosed event."
    )

    opportunity_summary: Optional[str] = Field(
        default=None,
        description="Short explanation of why the event may create a banking opportunity."
    )

    extra_notes: Optional[str] = Field(
        default=None,
        description=(
            "Concise, evidence-based notes from the supplied announcement that are not captured "
            "by another field and may help Syn Bank target the company."
        )
    )


class CompanyLevelExtDataResponse(BaseModel):
    """
    Will be sent to gemini to extract external data from pdfs
    """
    records: List[_CompanyLevelExtData] = Field(
        default_factory=list,
        description="Financial data records extracted from all supplied company financial documents."
    )


class SENSEventsResponse(BaseModel):
    """
    Will be sent to gemini to extract sens data
    """
    events: List[_SENSEvent] = Field(
        default_factory=list,
        description="Material SENS events extracted from all supplied SENS announcements."
    )


class DocumentFilenameValidation(BaseModel):
    """Gemini's assessment of one downloaded non-SENS document."""

    company: str = Field(
        description="Company name exactly as supplied in the validation input."
    )
    filename: str = Field(
        description="Filename exactly as supplied in the validation input."
    )
    is_explicitly_incorrect: bool = Field(
        description=(
            "True only when the filename itself contains explicit evidence "
            "that the document is incorrect; false for valid, generic, "
            "ambiguous, or inconclusive filenames."
        )
    )
    possibly_incorrect: bool = Field(
        description=(
            "True only when the filename contains specific suspicious evidence "
            "but not enough to establish an explicit error. Must be false for "
            "generic filenames and when is_explicitly_incorrect is true."
        )
    )
    reason: str = Field(
        description="Concise reason for the validation decision."
    )


class DocumentFilenameValidationResponse(BaseModel):
    """Structured response for validating downloaded report filenames."""

    documents: List[DocumentFilenameValidation] = Field(
        default_factory=list,
        description="Exactly one validation result for every supplied document."
    )
