"""
FastAPI backend for the banking share-of-wallet dashboard.

Reads data/mock_clients.json (generated by scripts/mock_data.py) and
serves it over a small REST API:

  GET  /api/clients               -> full array of client records
  GET  /api/clients/{id}          -> single client record by entity_id (e.g. "E01")
  POST /api/clients/{id}/briefing -> generate a briefing note for one client

CORS is enabled so a React frontend running on a different port
(e.g. http://localhost:3000 or :5173) can call this API directly.

Run with: uvicorn app:app --reload --port 4000
"""

import json
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.requests import Request
from fastapi.responses import JSONResponse

from prompts_briefing import build_briefing_prompt

app = FastAPI()

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "mock_clients.json"

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    # Match the Node/Express error shape: { "error": "..." } instead of
    # FastAPI's default { "detail": "..." }.
    return JSONResponse(status_code=exc.status_code, content={"error": exc.detail})


def load_clients():
    """
    Loads the client data fresh from disk on every request. The dataset is
    tiny (20 records) and this keeps the server in sync if mock_data.py is
    re-run without needing a restart.
    """
    with open(DATA_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


@app.get("/api/clients")
def get_clients():
    try:
        return load_clients()
    except Exception as err:
        print(f"Failed to read client data: {err}")
        raise HTTPException(status_code=500, detail="Failed to load client data")


@app.get("/api/clients/{client_id}")
def get_client(client_id: str):
    try:
        clients = load_clients()
    except Exception as err:
        print(f"Failed to read client data: {err}")
        raise HTTPException(status_code=500, detail="Failed to load client data")

    target = client_id.upper()
    client = next((c for c in clients if c["entity_id"].upper() == target), None)

    if client is None:
        raise HTTPException(status_code=404, detail=f"Client '{client_id}' not found")

    return client


@app.post("/api/clients/{client_id}/briefing")
def create_client_briefing(client_id: str):
    try:
        clients = load_clients()
    except Exception as err:
        print(f"Failed to read client data: {err}")
        raise HTTPException(status_code=500, detail="Failed to load client data")

    target = client_id.upper()
    client = next((c for c in clients if c["entity_id"].upper() == target), None)

    if client is None:
        raise HTTPException(status_code=404, detail=f"Client '{client_id}' not found")

    # Stub: proves the prompt builder is wired in correctly. Once Christiaan's
    # Gemini call is ready, this will send the built prompt to the model and
    # return its response instead of echoing the prompt back.
    prompt = build_briefing_prompt(client)
    return {"report": prompt}
