/**
 * Simple Express backend for the banking share-of-wallet dashboard.
 *
 * Reads data/mock_clients.json (generated by scripts/mock_data.py) and
 * serves it over a small REST API:
 *
 *   GET /api/clients      -> full array of client records
 *   GET /api/clients/:id  -> single client record by entity_id (e.g. "E01")
 *
 * CORS is enabled so a React frontend running on a different port
 * (e.g. http://localhost:3000 or :5173) can call this API directly.
 *
 * Run with: npm start
 */

const express = require("express");
const cors = require("cors");
const path = require("path");
const fs = require("fs");

const app = express();
const PORT = process.env.PORT || 4000;

const DATA_PATH = path.join(__dirname, "..", "data", "mock_clients.json");

app.use(cors());
app.use(express.json());

/**
 * Loads the client data fresh from disk on every request. The dataset is
 * tiny (20 records) and this keeps the server in sync if mock_data.py is
 * re-run without needing a restart.
 */
function loadClients() {
  const raw = fs.readFileSync(DATA_PATH, "utf-8");
  return JSON.parse(raw);
}

app.get("/api/clients", (req, res) => {
  try {
    const clients = loadClients();
    res.json(clients);
  } catch (err) {
    console.error("Failed to read client data:", err);
    res.status(500).json({ error: "Failed to load client data" });
  }
});

app.get("/api/clients/:id", (req, res) => {
  try {
    const clients = loadClients();
    const id = req.params.id.toUpperCase();
    const client = clients.find((c) => c.entity_id.toUpperCase() === id);

    if (!client) {
      return res.status(404).json({ error: `Client '${req.params.id}' not found` });
    }

    res.json(client);
  } catch (err) {
    console.error("Failed to read client data:", err);
    res.status(500).json({ error: "Failed to load client data" });
  }
});

app.listen(PORT, () => {
  console.log(`Share-of-wallet API listening on http://localhost:${PORT}`);
});
